stages:
  - test

test_job:
  stage: test
  tags:
    - new_runner_GB
  only:
    - master
  script:
    - echo "Запускает тесты"
    - mvn clean
    - mvn test
  artifacts:
    when: always
    paths:
      - allure-results