stages:
  - test

tags:
  - new_runner_GB

only:
  - master

test_job:
  stage: test
  script:
    - echo "Запускает тесты"
    - mvn clean
    - mvn test
  artifacts:
    when: always
    paths:
      - allure-results